version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
  api:
    build:
      context: ..
      dockerfile: infra/api.Dockerfile
    command: pnpm --filter @yia/api dev
    ports:
      - '4000:4000'
    depends_on:
      - redis
    environment:
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
      - REDIS_URL=redis://redis:6379
      - AI_RUNTIME_PROVIDER=local
    env_file:
      - ./api.env
  web:
    build:
      context: ..
      dockerfile: infra/web.Dockerfile
    command: pnpm --filter @yia/web dev -- --host
    ports:
      - '5173:5173'
    environment:
      - VITE_API_BASE=http://localhost:4000
    depends_on:
      - api
